## Exercise 1: Loading and Exploring the MNIST Dataset

In [2]:
import pandas as p
import numpy as np
import tensorflow as np

## Exercise 1: Loading and Exploring the MNIST Dataset
1. Import the MNIST dataset using the provided code.

In [23]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()


2. Display the shape and length of the training and test sets

In [24]:
print(train_images.shape)
print(len(train_labels))
print(test_images.shape)
print(len(test_labels))

(60000, 28, 28)
60000
(10000, 28, 28)
10000


3. Print the first few labels from the training set.

In [3]:

print(train_labels)


(60000, 28, 28)
60000
[5 0 4 ... 5 6 8]
(10000, 28, 28)
10000
[7 2 1 ... 4 5 6]


4. Display the shape of the test images.

In [34]:
print(test_labels) #only a vector right now; tensor 1

[7 2 1 ... 4 5 6]


## Exercise 2: Building the Neural Network 
1. Build a neural network using TensorFlow/Keras with the following architecture:

Input layer: Flatten the input images (28 x 28) into a vector.
Hidden layer: Dense layer with 512 units and ReLU activation function.
Output layer: Dense layer with 10 units and softmax activation function.

In [30]:
# The network architecture

from tensorflow import keras 
from tensorflow.keras import layers

model = keras.Sequential([
    layers.Flatten(input_shape = [28,28,1]), #reshapes first input layer
    layers.Dense(512, activation="relu"), #activation function (equation)
    layers.Dense(10, activation="softmax") #neurons must be 10 and will give you a probability values
])
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_2 (Flatten)         (None, 784)               0         
                                                                 
 dense_6 (Dense)             (None, 512)               401920    
                                                                 


 dense_7 (Dense)             (None, 10)                5130      
                                                                 
Total params: 407050 (1.55 MB)
Trainable params: 407050 (1.55 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


2. Compile the model using:

Optimizer: rmsprop
Loss function: sparse_categorical_crossentropy
Metrics: accuracy

In [35]:
# The compilation step

model.compile(optimizer="rmsprop",
              loss="sparse_categorical_crossentropy",
              metrics=["accuracy"])
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_2 (Flatten)         (None, 784)               0         
                                                                 
 dense_6 (Dense)             (None, 512)               401920    
                                                                 
 dense_7 (Dense)             (None, 10)                5130      
                                                                 
Total params: 407050 (1.55 MB)
Trainable params: 407050 (1.55 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


## Exercise 3: Preparing Image Data

1. Reshape and normalize the training and test images.

In [36]:
# already reshaped from model train_images = train_images.reshape((60000, 28 * 28))
# already reshaped from model test_images = test_images.reshape((10000, 28 * 28))
train_images = train_images.astype("float32") / 255
test_images = test_images.astype('float32') / 255


2. Print the shape of the reshaped training images.

In [37]:
train_images
test_images
#As you can see, it expanded from array to a vector

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

## Exercise 4 Fitting the Model
1. Train the model using the training images and labels.
2. Set the number of epochs to 5 and batch size to 128.

In [38]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 4s 8ms/step - loss: 2.2337 - accuracy: 0.2469
Epoch 2/5
469/469 [==============================] - 4s 9ms/step - loss: 1.6676 - accuracy: 0.5992
Epoch 3/5
469/469 [==============================] - 5s 10ms/step - loss: 1.0365 - accuracy: 0.7538
Epoch 4/5
469/469 [==============================] - 5s 11ms/step - loss: 0.7383 - accuracy: 0.8137
Epoch 5/5
469/469 [==============================] - 5s 11ms/step - loss: 0.5962 - accuracy: 0.8439


## Exercise 5: Making predictions and Evaluating the Model
1. Select the first 10 test images and use the trained model to make predictions.

In [41]:
test_digits = test_images[0:10]
predictions = model.predict(test_digits)

1/1 [==============================] - 0s 50ms/step


2. Print the predicted values for the first test image.

In [42]:
predictions[0]

array([4.5162323e-04, 4.4270288e-05, 1.5285875e-04, 1.2954953e-03,
       1.3097066e-03, 1.5259016e-03, 8.3298883e-06, 9.7326905e-01,
       3.2745820e-04, 2.1615198e-02], dtype=float32)

3. Print the class index with the highest probability for the first test image.

In [10]:
predictions[0].argmax()

7

4. Evaluate the model using the test images and labels.

In [45]:
predictions[0][7]

7

In [46]:
test_labels[0]

7

5. Print the test accuracy, precision, recall, and F1 score.

In [47]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"test_acc: {test_acc}")

313/313 [==============================] - 1s 4ms/step - loss: 0.5334 - accuracy: 0.8542
test_acc: 0.854200005531311
